### ISSUE TITLE
Μαρίνος - Μαρίνο

### ISSUE THREAD

**Issue by msfakianos** [chrispanag/greek-name-klitiki#8]
Probably due to commit [https://github.com/chrispanag/greek-name-klitiki/commit/3e7719beaa2f72f8d2c827c1ceaba305fc0986f2](url) the name Μαρίνος is transformed to "Μαρίνε" which is erroneous.

**Comment by chrispanag** [comment]
Wiktionary refers to the vocative form as "Μαρίνε"

https://el.wiktionary.org/wiki/Μαρίνος

It shouldn't be different than let's say "Ικτίνος" or "Κωνσταντίνος" or "Λατίνος". Nevertheless, I've heard people use "Μαρίνο" for the vocative. But I think it's due to sheer preference. I think we should stick to the official form here.

**Comment by msfakianos** [comment]
Agreed. Closing.
